// Base de données enrichie - 50+ variétés avec infos permaculture
// Chaque plante a : family (rotation), category (regroupement), tips détaillés (permaculture)

const vegetablesDatabase = {
    // ═══════════════════════════════════════════════════════════
    // TOMATES - 8 VARIÉTÉS
    // ═══════════════════════════════════════════════════════════
    tomate_cerise: {
        name: "Tomate Cerise",
        icon: "🍅",
        category: "tomate",
        family: "solanacees",
        growthDays: 65,
        spacing: 60, // cm entre plants
        maxHeight: 2.0, // hauteur max en mètres
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil (6-8h)",
        soilType: "Riche, bien drainé",
        nutrients: "Azote modéré, Phosphore, Potassium élevé",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Juin-Octobre",
        goodCompanions: ["basilic", "carotte_nantaise", "oignon", "persil"],
        badCompanions: ["pomme_de_terre", "fenouil", "chou"],
        // Températures pour conseils plantation
        seedingTemp: { min: 20, ideal: 24, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        tips: "PLANTATION : Avril-Mai (après dernières gelées). VARIÉTÉ : Très productive, fruits 15-30g. ESPACEMENT : 60cm entre plants. PAILLAGE : Paillis épais 10cm (paille, BRF) pour conserver humidité et éviter mildiou. PERMACULTURE : Planter avec basilic (repousse pucerons) et œillets d'Inde. Tuteurer en spirale. ASTUCE : Supprimer gourmands chaque semaine.",
        variety: "moderne"
    },
    
    tomate_coeur_de_boeuf: {
        name: "Tomate Cœur de Bœuf",
        icon: "🍅",
        category: "tomate",
        family: "solanacees",
        growthDays: 130,
        spacing: 60,
        maxHeight: 2.5,
        waterNeeds: "élevé (3-4 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Très riche, profond",
        nutrients: "Compost mature, purin d'ortie",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Juillet-Octobre",
        goodCompanions: ["basilic", "carotte_nantaise", "oignon"],
        badCompanions: ["pomme_de_terre", "fenouil"],
        seedingTemp: { min: 20, ideal: 24, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 6,
        tips: "PLANTATION : Avril-Mai (semis intérieur 6-8 semaines avant). VARIÉTÉ ANCIENNE : Fruits charnus 200-400g, chair dense. PAILLAGE : BRF de feuillus 15cm + compost en surface. PERMACULTURE : Gourmande, apport compost mensuel. Associer à la consoude (purin K). Tailler à 5-6 bouquets. CONSERVATION : Chair ferme, excellente en sauce.",
        variety: "ancienne"
    },
    
    tomate_noire_de_crimee: {
        name: "Tomate Noire de Crimée",
        icon: "🍅",
        category: "tomate",
        family: "solanacees",
        growthDays: 120,
        spacing: 60,
        maxHeight: 2.2,
        waterNeeds: "élevé (3-4 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche, bien drainé",
        nutrients: "Compost, purin d'ortie",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Juillet-Octobre",
        goodCompanions: ["basilic", "carotte_nantaise"],
        badCompanions: ["pomme_de_terre", "fenouil"],
        seedingTemp: { min: 20, ideal: 24, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 6,
        tips: "PLANTATION : Avril-Mai (semis intérieur 6-8 semaines avant). VARIÉTÉ RUSSE : Peau brun-noir, chair rouge foncé sucrée. PAILLAGE : Paille 10-15cm. PERMACULTURE : Résiste mieux au froid que les autres. Tailler modérément (7-8 bouquets). ASTUCE : Saveur optimale à pleine maturité (très sombre).",
        variety: "ancienne"
    },
    
    tomate_green_zebra: {
        name: "Tomate Green Zebra",
        icon: "🍅",
        category: "tomate",
        family: "solanacees",
        growthDays: 100,
        spacing: 60,
        maxHeight: 2.0,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche",
        nutrients: "Compost équilibré",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Juillet-Septembre",
        goodCompanions: ["basilic", "carotte_nantaise"],
        badCompanions: ["pomme_de_terre"],
        seedingTemp: { min: 20, ideal: 24, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 6,
        tips: "PLANTATION : Avril-Mai (semis intérieur 6-8 semaines avant). VARIÉTÉ ORIGINALE : Reste verte à maturité avec rayures jaunes, 100-150g. PAILLAGE : Mulch organique 8cm. PERMACULTURE : Productive, résiste à l'éclatement. Maturité = léger jaunissement + souplesse au toucher. SAVEUR : Acidulée, parfaite en salade.",
        variety: "ancienne"
    },
    
    tomate_ananas: {
        name: "Tomate Ananas",
        icon: "🍅",
        category: "tomate",
        family: "solanacees",
        growthDays: 130,
        spacing: 60,
        maxHeight: 2.5,
        waterNeeds: "élevé (3-4 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Très riche, profond",
        nutrients: "Compost abondant, fumier décomposé",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Août-Octobre",
        goodCompanions: ["basilic"],
        badCompanions: ["pomme_de_terre"],
        seedingTemp: { min: 20, ideal: 24, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 6,
        tips: "PLANTATION : Avril-Mai (semis intérieur 6-8 semaines avant). VARIÉTÉ GÉANTE : Bicolore jaune-rouge, 400-900g ! PAILLAGE : BRF 20cm + compost. PERMACULTURE : Très gourmande, purin d'ortie toutes les 2 semaines. Tuteurer solidement (poids). Tailler à 4-5 bouquets. ASTUCE : Chair fondante, peu de graines.",
        variety: "ancienne"
    },
    
    tomate_roma: {
        name: "Tomate Roma",
        icon: "🍅",
        category: "tomate",
        family: "solanacees",
        growthDays: 90,
        spacing: 60,
        maxHeight: 1.8,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche, bien drainé",
        nutrients: "Compost équilibré",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Juillet-Septembre",
        goodCompanions: ["basilic", "carotte_nantaise", "oignon"],
        badCompanions: ["pomme_de_terre", "fenouil"],
        seedingTemp: { min: 20, ideal: 24, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 6,
        tips: "PLANTATION : Avril-Mai (semis intérieur 6-8 semaines avant). VARIÉTÉ SAUCE : Forme allongée 60-90g, chair ferme peu juteuse. PAILLAGE : Paille 10cm. PERMACULTURE : Idéale conserves/sauces. Production groupée. Tailler modérément. CONSERVATION : Excellente en bocaux, séchage possible.",
        variety: "moderne"
    },
    
    tomate_saint_pierre: {
        name: "Tomate Saint-Pierre",
        icon: "🍅",
        category: "tomate",
        family: "solanacees",
        growthDays: 110,
        spacing: 60,
        maxHeight: 1.5,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche",
        nutrients: "Compost",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Juillet-Octobre",
        goodCompanions: ["basilic", "carotte_nantaise"],
        badCompanions: ["pomme_de_terre"],
        seedingTemp: { min: 20, ideal: 24, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 6,
        tips: "PLANTATION : Avril-Mai (semis intérieur 6-8 semaines avant). VARIÉTÉ FRANÇAISE : Ronde 120-180g, résistante maladies. PAILLAGE : Paille ou BRF 10cm. PERMACULTURE : Peu exigeante, adaptée débutants. Croissance déterminée (arrête de pousser). ASTUCE : Chair équilibrée, usage multiple.",
        variety: "traditionnelle"
    },
    
    tomate_cocktail: {
        name: "Tomate Cocktail",
        icon: "🍅",
        category: "tomate",
        family: "solanacees",
        growthDays: 70,
        spacing: 60,
        maxHeight: 2.0,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche, drainé",
        nutrients: "Compost léger",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Juin-Octobre",
        goodCompanions: ["basilic"],
        badCompanions: ["pomme_de_terre"],
        seedingTemp: { min: 20, ideal: 24, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 6,
        tips: "PLANTATION : Avril-Mai (semis intérieur 6-8 semaines avant). VARIÉTÉ INTERMÉDIAIRE : 40-60g, entre cerise et tomate normale. PAILLAGE : Mulch 8cm. PERMACULTURE : Très productive, récolte quotidienne. Tuteurage léger. APÉRITIF : Parfaite taille pour brochettes.",
        variety: "moderne"
    },
    
    // ═══════════════════════════════════════════════════════════
    // CAROTTES - 5 VARIÉTÉS
    // ═══════════════════════════════════════════════════════════
    carotte_nantaise: {
        name: "Carotte Nantaise",
        icon: "🥕",
        category: "carotte",
        family: "apiacees",
        growthDays: 90,
        spacing: 5,
        maxHeight: 0.4,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil à mi-ombre",
        soilType: "Sableux, léger, profond 30cm",
        nutrients: "Peu gourmande, pas de fumier frais",
        plantingPeriod: "Mars-Juillet",
        harvestPeriod: "Mai-Novembre",
        goodCompanions: ["tomate_cerise", "poireau", "oignon"],
        badCompanions: ["betterave"],
        seedingTemp: { min: 7, ideal: 15, max: 30 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "moderate",
        tips: "PLANTATION : Mars-Juillet (semis échelonnés tous les 15j). VARIÉTÉ CLASSIQUE : Cylindrique 15-18cm, sucrée. PAILLAGE : Léger 3-5cm (garde fraîcheur). PERMACULTURE : Semer avec radis (marque les rangs). Éclaircir à 5cm. Sol meuble ESSENTIEL (ameublir 30cm). ASTUCE : Mouche de la carotte → planter avec poireau ou oignon.",
        variety: "traditionnelle"
    },
    
    carotte_violette: {
        name: "Carotte Violette",
        icon: "🥕",
        category: "carotte",
        family: "apiacees",
        growthDays: 95,
        spacing: 5,
        maxHeight: 0.4,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Sableux, léger, profond",
        nutrients: "Pauvre à modéré",
        plantingPeriod: "Mars-Juillet",
        harvestPeriod: "Mai-Novembre",
        goodCompanions: ["tomate_cerise", "oignon"],
        badCompanions: [],
        seedingTemp: { min: 7, ideal: 15, max: 30 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "moderate",
        tips: "PLANTATION : Mars-Juillet (semis échelonnés). VARIÉTÉ ANCIENNE : Peau violette, cœur orange, 15-20cm. Riche en anthocyanes (antioxydants). PAILLAGE : Mulch léger 5cm. PERMACULTURE : Résiste mieux au froid. Saveur douce légèrement sucrée. CUISINE : Couleur perdue à la cuisson, meilleure crue.",
        variety: "ancienne"
    },
    
    carotte_jaune: {
        name: "Carotte Jaune",
        icon: "🥕",
        category: "carotte",
        family: "apiacees",
        growthDays: 90,
        spacing: 5,
        maxHeight: 0.4,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Léger, sableux",
        nutrients: "Peu exigeante",
        plantingPeriod: "Mars-Juillet",
        harvestPeriod: "Mai-Novembre",
        goodCompanions: ["tomate_cerise", "oignon"],
        badCompanions: ["betterave"],
        seedingTemp: { min: 7, ideal: 15, max: 30 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "moderate",
        tips: "PLANTATION : Mars-Juillet (semis échelonnés). VARIÉTÉ ORIGINALE : Jaune vif, 15-18cm, très sucrée. PAILLAGE : Mulch 5cm. PERMACULTURE : Moins sensible à la mouche. Saveur douce, texture croquante. DÉCORATION : Colorée en salade, couleur stable à la cuisson.",
        variety: "ancienne"
    },
    
    carotte_blanche: {
        name: "Carotte Blanche",
        icon: "🥕",
        category: "carotte",
        family: "apiacees",
        growthDays: 100,
        spacing: 5,
        maxHeight: 0.4,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Profond, léger",
        nutrients: "Modéré",
        plantingPeriod: "Mars-Juin",
        harvestPeriod: "Juin-Octobre",
        goodCompanions: ["oignon", "poireau"],
        badCompanions: [],
        seedingTemp: { min: 7, ideal: 15, max: 30 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "moderate",
        tips: "PLANTATION : Mars-Juillet (semis échelonnés). VARIÉTÉ RARE : Blanc-crème, forme de panais. Racine ancienne d'avant sélection orange. PAILLAGE : Léger 5cm. PERMACULTURE : Saveur douce, légèrement anisée. Résiste bien au froid. HISTOIRE : Carotte originelle avant mutation orange (XVIe siècle).",
        variety: "ancienne"
    },
    
    carotte_chantenay: {
        name: "Carotte Chantenay",
        icon: "🥕",
        category: "carotte",
        family: "apiacees",
        growthDays: 85,
        spacing: 5,
        maxHeight: 0.3,
        waterNeeds: "faible (1-2 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Argileux acceptable, moins profond",
        nutrients: "Peu gourmande",
        plantingPeriod: "Mars-Juillet",
        harvestPeriod: "Juin-Novembre",
        goodCompanions: ["oignon", "tomate_cerise"],
        badCompanions: ["betterave"],
        seedingTemp: { min: 7, ideal: 15, max: 30 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "moderate",
        tips: "PLANTATION : Mars-Juillet (idéale sol lourd). VARIÉTÉ RUSTIQUE : Conique courte 12-15cm, adaptée sols lourds. PAILLAGE : Mulch 5-8cm. PERMACULTURE : Idéale si sol peu profond ou caillouteux. Très résistante, bonne conservation hivernale. ASTUCE : Chair ferme, excellente en conserve.",
        variety: "traditionnelle"
    },
    
    // ═══════════════════════════════════════════════════════════
    // SALADES - 4 VARIÉTÉS
    // ═══════════════════════════════════════════════════════════
    laitue_batavia: {
        name: "Laitue Batavia",
        icon: "🥬",
        category: "salade",
        family: "asteracees",
        growthDays: 55,
        spacing: 30,
        maxHeight: 0.3,
        waterNeeds: "élevé (3-4 L/m²/jour)",
        sunlight: "Mi-ombre été, soleil printemps/automne",
        soilType: "Frais, riche en humus",
        nutrients: "Azote, compost",
        plantingPeriod: "Mars-Septembre",
        harvestPeriod: "Avril-Novembre",
        goodCompanions: ["carotte_nantaise", "radis", "fraise"],
        badCompanions: ["persil"],
        seedingTemp: { min: 5, ideal: 18, max: 24 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "light",
        tips: "PLANTATION : Mars-Juin + Août-Septembre (semis échelonnés). VARIÉTÉ CROQUANTE : Feuilles épaisses, résiste chaleur. PAILLAGE : Éviter autour du collet (pourriture), pailler entre rangs. PERMACULTURE : Semis échelonnés tous les 15j. Arrosage régulier matin/soir. ASTUCE : Récolte feuille par feuille ou pied entier.",
        variety: "moderne"
    },
    
    laitue_feuille_de_chene: {
        name: "Laitue Feuille de Chêne",
        icon: "🥬",
        category: "salade",
        family: "asteracees",
        growthDays: 50,
        spacing: 25,
        maxHeight: 0.3,
        waterNeeds: "élevé (3-4 L/m²/jour)",
        sunlight: "Mi-ombre",
        soilType: "Riche, frais",
        nutrients: "Compost mûr",
        plantingPeriod: "Mars-Septembre",
        harvestPeriod: "Avril-Novembre",
        goodCompanions: ["radis", "carotte_nantaise"],
        badCompanions: ["persil"],
        seedingTemp: { min: 5, ideal: 18, max: 24 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "light",
        tips: "PLANTATION : Mars-Juin + Août-Septembre. VARIÉTÉ TENDRE : Feuilles découpées tendres, 2 versions (verte/rouge). PAILLAGE : Léger entre rangs. PERMACULTURE : Monte lentement en graine. Récolte feuille à feuille prolonge production. ASTUCE : Fragile, consommer rapidement après récolte.",
        variety: "traditionnelle"
    },

    roquette: {
        name: "Roquette",
        icon: "🥬",
        category: "salade",
        family: "brassicacees",
        growthDays: 30,
        spacing: 15,
        maxHeight: 0.2,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Mi-ombre (évite montée graine)",
        soilType: "Léger, frais",
        nutrients: "Peu exigeante",
        plantingPeriod: "Mars-Septembre",
        harvestPeriod: "Avril-Novembre",
        goodCompanions: ["tomate_cerise", "carotte_nantaise"],
        badCompanions: [],
        seedingTemp: { min: 8, ideal: 15, max: 25 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "light",
        tips: "POUSSE RAPIDE : 20-30 jours, saveur poivrée/moutardée. PAILLAGE : Léger 3cm. PERMACULTURE : Monte vite en graine par chaleur. Semis échelonnés. Laisser fleurir pour abeilles. Couper 3cm au-dessus du sol → repousse. ASTUCE : Plus vieille = plus piquante.",
        variety: "moderne"
    },
    
    mache: {
        name: "Mâche",
        icon: "🥬",
        category: "salade",
        family: "caprifoliacees",
        growthDays: 70,
        spacing: 10,
        maxHeight: 0.2,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Mi-ombre à ombre",
        soilType: "Tous types",
        nutrients: "Peu exigeante",
        plantingPeriod: "Août-Octobre",
        harvestPeriod: "Octobre-Mars",
        goodCompanions: ["poireau", "oignon"],
        badCompanions: [],
        seedingTemp: { min: 5, ideal: 12, max: 20 },
        plantingTemp: { soil: 5, airNight: -5, airDay: 5 },
        frostTolerance: "very_good",
        tips: "PLANTATION : Août-Octobre (culture d'hiver). CULTURE D'HIVER : Résiste -10°C, parfaite hors-saison. PAILLAGE : Paille 5cm protège du gel. PERMACULTURE : Semer dense, éclaircir à 5cm. Culture intercalaire (entre rangs poireaux). Se ressème spontanément. ASTUCE : Récolte rosette entière au couteau.",
        variety: "traditionnelle"
    },
    
    // ═══════════════════════════════════════════════════════════
    // HARICOTS - 3 VARIÉTÉS
    // ═══════════════════════════════════════════════════════════
    haricot_vert_nain: {
        name: "Haricot Vert Nain",
        icon: "🌿",
        category: "haricot",
        family: "fabacees",
        growthDays: 60,
        spacing: 40,
        maxHeight: 0.5,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Léger, bien drainé, pas trop riche",
        nutrients: "FIXE L'AZOTE - Peu d'engrais nécessaire",
        plantingPeriod: "Mai-Juillet (après gelées)",
        harvestPeriod: "Juillet-Octobre",
        goodCompanions: ["pomme_de_terre", "carotte_nantaise", "mais", "courgette"],
        badCompanions: ["oignon", "ail", "poireau", "fenouil"],
        seedingTemp: { min: 12, ideal: 20, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        tips: "PLANTATION : Mai-Juillet (APRÈS GELÉES). VARIÉTÉ PRODUCTIVE : Buissonnant 40cm, sans tuteur. PAILLAGE : Après levée, paille 5cm. PERMACULTURE : ENRICHIT LE SOL (azote via rhizobiums). Semer 5cm profondeur par groupes de 5. Butter légèrement. ROTATION : Parfait après solanacées gourmandes. ASTUCE : Récolte avant maturité complète (gousses fines).",
        variety: "moderne"
    },
    
    haricot_a_rames: {
        name: "Haricot à Rames",
        icon: "🌿",
        category: "haricot",
        family: "fabacees",
        growthDays: 70,
        spacing: 50,
        maxHeight: 2.5,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche, profond",
        nutrients: "Fixe azote, compost modéré",
        plantingPeriod: "Mai-Juin",
        harvestPeriod: "Juillet-Octobre",
        goodCompanions: ["mais", "courgette", "potiron"],
        badCompanions: ["oignon", "ail"],
        seedingTemp: { min: 12, ideal: 20, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        tips: "PLANTATION : Mai-Juillet (APRÈS GELÉES, sol >15°C). GRIMPANT : 2-3m, tuteurs obligatoires. PAILLAGE : BRF 8cm au pied. PERMACULTURE : Système des 3 sœurs (maïs=tuteur, courge=couvre-sol, haricot=azote). Production prolongée. Ramer en tipi ou rangs. RENDEMENT : Supérieur aux nains. Récolte régulière stimule production.",
        variety: "traditionnelle"
    },
    
    haricot_beurre: {
        name: "Haricot Beurre",
        icon: "🌿",
        category: "haricot",
        family: "fabacees",
        growthDays: 65,
        spacing: 40,
        maxHeight: 0.5,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Léger, drainé",
        nutrients: "Fixe azote",
        plantingPeriod: "Mai-Juillet",
        harvestPeriod: "Juillet-Septembre",
        goodCompanions: ["carotte_nantaise", "pomme_de_terre"],
        badCompanions: ["oignon", "ail"],
        seedingTemp: { min: 12, ideal: 20, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        tips: "PLANTATION : Mai-Juillet (APRÈS GELÉES, sol >15°C). GOUSSES JAUNES : Tendres, sans fil, saveur douce. PAILLAGE : Paille 5cm. PERMACULTURE : Enrichit le sol. Nain ou à rames selon variété. CUISINE : Excellente saveur beurrée, texture fondante. Consommer rapidement (fragile).",
        variety: "traditionnelle"
    },

    // AUTRES LÉGUMES ESSENTIELS
    courgette: {
        name: "Courgette Verte",
        icon: "🥒",
        category: "courgette",
        family: "cucurbitacees",
        growthDays: 60,
        spacing: 100,
        maxHeight: 0.6,
        waterNeeds: "élevé (3-4 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche en humus, profond",
        nutrients: "TRÈS GOURMANDE - Compost mature, fumier décomposé",
        plantingPeriod: "Avril-Juin",
        harvestPeriod: "Juin-Octobre",
        goodCompanions: ["mais", "haricot_vert_nain", "basilic", "oignon"],
        badCompanions: ["pomme_de_terre"],
        seedingTemp: { min: 15, ideal: 22, max: 28 },
        plantingTemp: { soil: 18, airNight: 13, airDay: 18 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 4,
        tips: "PLANTATION : Mai-Juillet (après gelées, sol >10°C). PRODUCTION ABONDANTE : 1 pied = 3-6kg. PAILLAGE : BRF ou paille épais 15cm (garde humidité). PERMACULTURE : Très gourmande, apporter compost mûr au fond du trou. Arrosage au pied. Récolte jeune 15-20cm (meilleure saveur, stimule production). ASTUCE : Fleurs mâles comestibles farcies.",
        variety: "traditionnelle"
    },

    aubergine: {
        name: "Aubergine",
        icon: "🍆",
        category: "aubergine",
        family: "solanacees",
        growthDays: 150,
        spacing: 60,
        maxHeight: 1.0,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil, chaleur",
        soilType: "Riche, bien drainé, chaud",
        nutrients: "Compost, potasse",
        plantingPeriod: "Mai (après gelées)",
        harvestPeriod: "Juillet-Septembre",
        goodCompanions: ["haricot_vert_nain", "thym"],
        badCompanions: ["pomme_de_terre", "tomate_cerise"],
        seedingTemp: { min: 22, ideal: 26, max: 35 },
        plantingTemp: { soil: 21, airNight: 15, airDay: 20 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 8,
        tips: "PLANTATION : Avril-Mai (semis intérieur 6-8 semaines avant). CHALEUR EXIGÉE : Serre recommandée climat frais. PAILLAGE : Noir (plastique ou paillette) réchauffe sol. PERMACULTURE : Gourmande, purin d'ortie + consoude. Tailler à 3-4 fruits. Doryphores possibles → ramassage manuel. RÉCOLTE : Peau brillante = maturité parfaite.",
        variety: "traditionnelle"
    },

    poivron: {
        name: "Poivron",
        icon: "🌶️",
        category: "poivron",
        family: "solanacees",
        growthDays: 140,
        spacing: 50,
        maxHeight: 0.9,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil, chaleur",
        soilType: "Riche, bien drainé",
        nutrients: "Compost équilibré",
        plantingPeriod: "Mai",
        harvestPeriod: "Juillet-Octobre",
        goodCompanions: ["basilic", "oignon", "carotte_nantaise"],
        badCompanions: ["fenouil", "chou"],
        seedingTemp: { min: 20, ideal: 25, max: 30 },
        plantingTemp: { soil: 18, airNight: 13, airDay: 18 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 8,
        tips: "PLANTATION : Avril-Mai (semis intérieur 6-8 semaines avant). COULEURS : Vert → Jaune/Rouge/Orange (maturité). PAILLAGE : Paille 10cm. PERMACULTURE : Besoin chaleur, serre/tunnel conseillé. Tuteurage si chargé. Arrosage régulier sans excès. PATIENCE : Vert=immature (goût amer), attendre coloration complète. ASTUCE : Maturité complète = +vitamines.",
        variety: "traditionnelle"
    },

    pomme_de_terre: {
        name: "Pomme de terre",
        icon: "🥔",
        category: "pomme_de_terre",
        family: "solanacees",
        growthDays: 120,
        spacing: 40,
        maxHeight: 0.6,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Léger, meuble, profond",
        nutrients: "TRÈS GOURMANDE - Compost mature",
        plantingPeriod: "Mars-Mai",
        harvestPeriod: "Juin-Septembre",
        goodCompanions: ["haricot_vert_nain", "mais", "chou", "pois"],
        badCompanions: ["tomate_cerise", "tomate_coeur_de_boeuf", "courgette", "aubergine", "concombre"],
        seedingTemp: { min: 7, ideal: 18, max: 25 },
        plantingTemp: { soil: 10, airNight: 7, airDay: 12 },
        frostTolerance: "light",
        tips: "PLANTATION : Mars-Mai (plantation tubercules). BUTTAGE ESSENTIEL : Butter 3 fois pour forcer tubercules et éviter verdissement. PAILLAGE : 20-30cm paille (remplace buttage + protège doryphores). PERMACULTURE : Rotation 4 ans minimum. Planter avec œillets d'Inde. Germes 2-3cm avant plantation. VARIÉTÉS : Précoces (90j), demi-saison (110j), tardives (140j). CONSERVATION : Cave sombre 5-10°C.",
        variety: "traditionnelle"
    },

    oignon: {
        name: "Oignon",
        icon: "🧅",
        category: "oignon",
        family: "alliacees",
        growthDays: 150,
        spacing: 10,
        maxHeight: 0.5,
        waterNeeds: "faible (1-2 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Bien drainé, pas trop riche",
        nutrients: "PEU GOURMAND - Sol pauvre OK",
        plantingPeriod: "Février-Avril",
        harvestPeriod: "Juillet-Septembre",
        goodCompanions: ["carotte_nantaise", "tomate_cerise", "laitue_batavia", "fraise"],
        badCompanions: ["pois", "haricot_vert_nain", "feve"],
        seedingTemp: { min: 5, ideal: 15, max: 25 },
        plantingTemp: { soil: 5, airNight: 0, airDay: 10 },
        frostTolerance: "good",
        tips: "PLANTATION : Février-Avril (bulbilles) ou Août-Septembre (semis). REPOUSSE RAVAGEURS : Éloigne mouche de la carotte, pucerons. PAILLAGE : Éviter (bulbe a besoin soleil direct). PERMACULTURE : Planter avec carottes (protection mutuelle). PAS d'excès d'eau. Coucher fanes 3 semaines avant récolte. SÉCHAGE : 2-3 jours plein soleil. CONSERVATION : Tresse, cave sèche 6-8 mois.",
        variety: "traditionnelle"
    },

    ail: {
        name: "Ail",
        icon: "🧄",
        category: "oignon",
        family: "alliacees",
        growthDays: 240,
        spacing: 15,
        maxHeight: 0.4,
        waterNeeds: "faible (1-2 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Léger, drainant, pas d'humidité stagnante",
        nutrients: "PEU GOURMAND",
        plantingPeriod: "Octobre-Mars (selon variété)",
        harvestPeriod: "Juin-Juillet",
        goodCompanions: ["tomate_cerise", "fraise", "carotte_nantaise"],
        badCompanions: ["pois", "haricot_vert_nain", "chou"],
        seedingTemp: { min: 5, ideal: 15, max: 25 },
        plantingTemp: { soil: 5, airNight: -5, airDay: 5 },
        frostTolerance: "excellent",
        tips: "FONGICIDE NATUREL : Protège fraisiers et rosiers des maladies. PAILLAGE : Éviter (besoin soleil). PERMACULTURE : Planter caïeux pointe vers haut, 3cm profondeur. VARIÉTÉS : Blanc (automne, rustique), Rose/Violet (printemps, doux). RÉCOLTE : Fanes jaunies 2/3. Séchage ombragé ventilé. CONSERVATION : Tresse, 1 an.",
        variety: "traditionnelle"
    },

    epinard: {
        name: "Épinard",
        icon: "🥬",
        category: "epinard",
        family: "amaranthacees",
        growthDays: 50,
        spacing: 10,
        maxHeight: 0.3,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Mi-ombre (évite montée graine)",
        soilType: "Riche en azote, frais",
        nutrients: "Compost mûr, azote",
        plantingPeriod: "Mars-Avril, Août-Septembre",
        harvestPeriod: "Avril-Novembre",
        goodCompanions: ["fraise", "haricot_vert_nain", "pois"],
        badCompanions: ["betterave"],
        seedingTemp: { min: 5, ideal: 15, max: 25 },
        plantingTemp: { soil: 8, airNight: 0, airDay: 10 },
        frostTolerance: "excellent",
        tips: "PLANTATION : Avril-Mai (semis intérieur 6-8 semaines avant). CULTURE RAPIDE : 6-8 semaines. PAILLAGE : 5cm maintient fraîcheur. PERMACULTURE : Monte vite en graine si chaleur/manque d'eau. Semer épais, éclaircir 10cm. Récolte feuille par feuille. Culture printemps/automne idéale. ASTUCE : Variétés d'hiver résistent gel.",
        variety: "traditionnelle"
    },

    chou: {
        name: "Chou cabus",
        icon: "🥬",
        category: "chou",
        family: "brassicacees",
        growthDays: 140,
        spacing: 50,
        maxHeight: 0.6,
        waterNeeds: "élevé (3-4 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche, frais, calcaire apprécié",
        nutrients: "TRÈS GOURMAND - Compost, azote",
        plantingPeriod: "Mars-Juillet",
        harvestPeriod: "Juin-Mars",
        goodCompanions: ["pomme_de_terre", "betterave", "oignon", "menthe"],
        badCompanions: ["tomate_cerise", "fraise", "ail"],
        seedingTemp: { min: 10, ideal: 18, max: 25 },
        plantingTemp: { soil: 10, airNight: 5, airDay: 10 },
        frostTolerance: "excellent",
        tips: "PLANTATION : Mars-Juin (selon variété). RAVAGEURS : Piéride (chenilles vertes) → voile anti-insectes ou Bt. Altises → arrosage. PAILLAGE : 10cm. PERMACULTURE : Gourmand, compost abondant. Butter au pied. Associer menthe/thym (repousse piéride). Planter avec tomates ERREUR (allélopathie négative). VARIÉTÉS : Printemps, été, automne/hiver. CONSERVATION : Cave 3-4 mois.",
        variety: "traditionnelle"
    },

    radis: {
        name: "Radis",
        icon: "🌰",
        category: "radis",
        family: "brassicacees",
        growthDays: 25,
        spacing: 5,
        maxHeight: 0.2,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Mi-ombre à soleil",
        soilType: "Léger, frais, meuble",
        nutrients: "PEU GOURMAND",
        plantingPeriod: "Mars-Septembre",
        harvestPeriod: "Avril-Novembre",
        goodCompanions: ["laitue_batavia", "carotte_nantaise", "tomate_cerise"],
        badCompanions: ["chou"],
        seedingTemp: { min: 6, ideal: 18, max: 25 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "light",
        tips: "PLANTATION : Mars-Septembre (semis échelonnés). POUSSE RAPIDE : 18-25 jours ! PAILLAGE : Léger 2-3cm (garde fraîcheur). PERMACULTURE : Culture intercalaire parfaite (entre carottes/salades). Semer clair. ARROSAGE régulier CRUCIAL (sinon radis piquant, creux, fibreux). Récolte rapide dès bonne taille. ASTUCE : Semer tous les 10-15j pour récolte continue.",
        variety: "traditionnelle"
    },

    betterave: {
        name: "Betterave",
        icon: "🟣",
        category: "betterave",
        family: "amaranthacees",
        growthDays: 100,
        spacing: 10,
        maxHeight: 0.4,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Profond, frais, léger",
        nutrients: "Modéré, compost mûr",
        plantingPeriod: "Avril-Juin",
        harvestPeriod: "Juillet-Octobre",
        goodCompanions: ["oignon", "chou", "laitue_batavia"],
        badCompanions: ["carotte_nantaise", "poireau"],
        seedingTemp: { min: 10, ideal: 18, max: 26 },
        plantingTemp: { soil: 10, airNight: 7, airDay: 12 },
        frostTolerance: "moderate",
        tips: "PLANTATION : Avril-Juin (semis échelonnés). RACINE SUCRÉE : Rouge classique ou jaune/blanche. PAILLAGE : 5-8cm. PERMACULTURE : Éclaircir à 10cm (glomérules = plusieurs graines). Feuilles jeunes comestibles (cuire comme épinards). Récolte avant gelées. CONSERVATION : Cave sable humide 4-5 mois. ASTUCE : Ne pas couper racine pivot (saignement).",
        variety: "traditionnelle"
    },

    basilic: {
        name: "Basilic",
        icon: "🌿",
        category: "herbe",
        family: "lamiacees",
        growthDays: 60,
        spacing: 25,
        maxHeight: 0.5,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil, chaleur",
        soilType: "Riche, drainant, chaud",
        nutrients: "Compost léger",
        plantingPeriod: "Mai-Juin (après gelées)",
        harvestPeriod: "Juin-Octobre",
        goodCompanions: ["tomate_cerise", "tomate_coeur_de_boeuf", "poivron", "aubergine"],
        badCompanions: [],
        seedingTemp: { min: 15, ideal: 22, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        tips: "PLANTATION : Mai-Juin (APRÈS GELÉES). COMPAGNON PARFAIT TOMATES : Repousse pucerons, aleurodes, améliore goût. PAILLAGE : Léger 3cm. PERMACULTURE : Pincer RÉGULIÈREMENT sommets (favorise ramification, retarde floraison). Arrosage matin (évite mildiou). GEL MORTEL. VARIÉTÉS : Grand vert, pourpre, citron, thaï. CONSERVATION : Congeler ou huile d'olive.",
        variety: "traditionnelle"
    },

    persil: {
        name: "Persil",
        icon: "🌿",
        category: "herbe",
        family: "apiacees",
        growthDays: 80,
        spacing: 20,
        maxHeight: 0.4,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Mi-ombre",
        soilType: "Riche, frais, profond",
        nutrients: "Compost",
        plantingPeriod: "Mars-Août",
        harvestPeriod: "Mai-Novembre",
        goodCompanions: ["tomate_cerise"],
        badCompanions: ["laitue_batavia"],
        seedingTemp: { min: 10, ideal: 18, max: 25 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "moderate",
        tips: "PLANTATION : Mars-Septembre (semis échelonnés). GERMINATION LENTE : 3-4 semaines. PAILLAGE : 3cm garde fraîcheur. PERMACULTURE : Faire tremper graines 24h avant semis (accélère germination). Bisannuel (monte en graine année 2). Couper régulièrement stimule production. VARIÉTÉS : Plat (arôme puissant), Frisé (décoration). ASTUCE : Congèle très bien ciselé.",
        variety: "traditionnelle"
    },

    menthe: {
        name: "Menthe",
        icon: "🌿",
        category: "herbe",
        family: "lamiacees",
        growthDays: 60,
        spacing: 30,
        maxHeight: 0.5,
        waterNeeds: "élevé (3-4 L/m²/jour)",
        sunlight: "Mi-ombre",
        soilType: "Frais, riche, humide",
        nutrients: "Compost",
        plantingPeriod: "Mars-Mai",
        harvestPeriod: "Mai-Octobre",
        goodCompanions: ["chou", "tomate_cerise"],
        badCompanions: [],
        seedingTemp: { min: 10, ideal: 18, max: 25 },
        plantingTemp: { soil: 8, airNight: 5, airDay: 10 },
        frostTolerance: "excellent",
        tips: "PLANTATION : Mars-Juin (division ou bouture). ATTENTION ENVAHISSANTE ! Rhizomes traçants colonisent rapidement. PAILLAGE : 5cm garde humidité. PERMACULTURE : Planter en POT enterré (limite expansion) ou zone dédiée. Couper avant floraison (feuilles tendres). Division touffes tous les 3 ans. VARIÉTÉS : Verte, poivrée, chocolat, pomme. RÉPULSIF : Éloigne pucerons.",
        variety: "traditionnelle"
    },

    thym: {
        name: "Thym",
        icon: "🌿",
        category: "herbe",
        family: "lamiacees",
        growthDays: 90,
        spacing: 30,
        maxHeight: 0.3,
        waterNeeds: "faible (1-2 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Léger, drainant, caillouteux OK",
        nutrients: "PAUVRE - Pas d'engrais",
        plantingPeriod: "Mars-Mai",
        harvestPeriod: "Mai-Septembre",
        goodCompanions: ["chou", "fraise", "aubergine"],
        badCompanions: [],
        seedingTemp: { min: 15, ideal: 20, max: 25 },
        plantingTemp: { soil: 10, airNight: 5, airDay: 10 },
        frostTolerance: "excellent",
        tips: "PLANTATION : Mars-Juin (semis ou division). MÉDITERRANÉEN : Résiste sécheresse, adore sols pauvres. PAS DE PAILLAGE (drainage essentiel). PERMACULTURE : Vivace persistant 4-6 ans. Tailler après floraison. Drainage CRUCIAL (meurt si humidité stagnante). VARIÉTÉS : Commun, citron, serpolet. PROPRIÉTÉS : Antiseptique, digestif.",
        variety: "traditionnelle"
    },

    potiron: {
        name: "Potiron",
        icon: "🎃",
        category: "courge",
        family: "cucurbitacees",
        growthDays: 120,
        spacing: 150,
        maxHeight: 0.5,
        waterNeeds: "élevé (3-4 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Très riche, profond",
        nutrients: "TRÈS GOURMAND - Fumier, compost abondant",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Septembre-Novembre",
        goodCompanions: ["mais", "haricot_a_rames"],
        badCompanions: ["pomme_de_terre"],
        seedingTemp: { min: 18, ideal: 24, max: 35 },
        plantingTemp: { soil: 18, airNight: 13, airDay: 18 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 3,
        tips: "PLANTATION : Mai-Juin (APRÈS GELÉES). GÉANT : 1 plant = 20-30kg ! PAILLAGE : Épais 15-20cm (garde humidité). PERMACULTURE : Planter sur tas de compost. Système 3 sœurs. Pincer après 3-4 fruits (concentre énergie). Pédoncule 3-4cm à la récolte (conservation). POLLINISATION : Manuelle possible si peu d'insectes. CONSERVATION : Cave fraîche 6-12 mois.",
        variety: "traditionnelle"
    },

    butternut: {
        name: "Courge Butternut",
        icon: "🎃",
        category: "courge",
        family: "cucurbitacees",
        growthDays: 110,
        spacing: 120,
        maxHeight: 0.5,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche",
        nutrients: "Compost",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Septembre-Octobre",
        goodCompanions: ["mais", "haricot_a_rames"],
        badCompanions: [],
        seedingTemp: { min: 18, ideal: 24, max: 35 },
        plantingTemp: { soil: 18, airNight: 13, airDay: 18 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 3,
        tips: "PLANTATION : Mai-Juin (APRÈS GELÉES). FORME CARACTÉRISTIQUE : Poire allongée, chair orangée sucrée. PAILLAGE : 15cm. PERMACULTURE : Moins gourmande que potiron. Chair ferme, peu de graines (bon rendement chair). Peau fine = épluchage facile. CONSERVATION : Excellente 6-8 mois cave. CUISINE : Purée, soupe, rôtie.",
        variety: "moderne"
    },

    pois: {
        name: "Pois",
        icon: "🌱",
        category: "pois",
        family: "fabacees",
        growthDays: 90,
        spacing: 5,
        maxHeight: 1.8,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Léger, calcaire apprécié",
        nutrients: "FIXE L'AZOTE - Peu d'engrais",
        plantingPeriod: "Février-Mai",
        harvestPeriod: "Mai-Août",
        goodCompanions: ["carotte_nantaise", "radis", "mais"],
        badCompanions: ["oignon", "ail", "poireau"],
        seedingTemp: { min: 4, ideal: 15, max: 24 },
        plantingTemp: { soil: 5, airNight: 0, airDay: 10 },
        frostTolerance: "excellent",
        tips: "PLANTATION : Février-Mai (résiste gel léger). ENRICHIT SOL : Azote fixé = +100kg N/ha ! PAILLAGE : Après levée 5cm. PERMACULTURE : Ramer variétés à rame. Protège carottes (ombre partielle OK). Culture fraîche (printemps/automne). Laisser racines en terre après récolte (azote). VARIÉTÉS : Nain, à ramer, mangetout, gourmand. ASTUCE : Trempage 12h accélère germination.",
        variety: "traditionnelle"
    },

    feve: {
        name: "Fève",
        icon: "🍃",
        category: "feve",
        family: "fabacees",
        growthDays: 100,
        spacing: 15,
        maxHeight: 1.2,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche, argileux acceptable",
        nutrients: "FIXE L'AZOTE",
        plantingPeriod: "Février-Avril",
        harvestPeriod: "Mai-Juillet",
        goodCompanions: ["pomme_de_terre", "laitue_batavia"],
        badCompanions: ["oignon", "ail"],
        seedingTemp: { min: 5, ideal: 15, max: 25 },
        plantingTemp: { soil: 5, airNight: -2, airDay: 8 },
        frostTolerance: "excellent",
        tips: "PLANTATION : Février-Mai (semis précoce, résiste gel léger). CULTURE FROIDE : Semis précoce, résiste gel léger. PAILLAGE : 5-8cm. PERMACULTURE : Enrichit sol (azote). PUCERONS NOIRS : Pincer têtes dès apparition 1ers pucerons (zone préférée). Butter plants. VARIÉTÉS : Aguadulce (grosse), Séville (rustique). CUISINE : Jeune fraîche ou sèche conserve. ASTUCE : Enfouir plants après récolte (engrais vert).",
        variety: "traditionnelle"
    },

    mais: {
        name: "Maïs",
        icon: "🌽",
        category: "mais",
        family: "poacees",
        growthDays: 100,
        spacing: 40,
        maxHeight: 2.3,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche, profond, chaud",
        nutrients: "GOURMAND - Azote, compost",
        plantingPeriod: "Avril-Mai (sol >10°C)",
        harvestPeriod: "Août-Septembre",
        goodCompanions: ["haricot_a_rames", "courge", "courgette", "potiron"],
        badCompanions: ["tomate_cerise", "celeri"],
        seedingTemp: { min: 12, ideal: 22, max: 30 },
        plantingTemp: { soil: 15, airNight: 10, airDay: 15 },
        frostTolerance: "none",
        tips: "PLANTATION : Mai-Juin (APRÈS GELÉES, sol >10°C). SYSTÈME 3 SŒURS : Maïs=tuteur haricots, Courge=couvre-sol, Haricot=azote. PAILLAGE : 10cm après 30cm hauteur. PERMACULTURE : Planter en BLOCS (minimum 4x4) pour pollinisation (vent). Butter au pied (ancrage). Arrosage important floraison/remplissage. RÉCOLTE : Grains laiteux, soies brunies. ASTUCE : Épis barbe dorée = maturité.",
        variety: "traditionnelle"
    },

    concombre: {
        name: "Concombre",
        icon: "🥒",
        category: "concombre",
        family: "cucurbitacees",
        growthDays: 70,
        spacing: 60,
        maxHeight: 1.8,
        waterNeeds: "élevé (3-4 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche, frais, bien drainé",
        nutrients: "GOURMAND - Compost mature",
        plantingPeriod: "Avril-Mai",
        harvestPeriod: "Juillet-Septembre",
        goodCompanions: ["haricot_vert_nain", "mais", "pois", "basilic"],
        badCompanions: ["tomate_cerise", "pomme_de_terre"],
        seedingTemp: { min: 15, ideal: 25, max: 35 },
        plantingTemp: { soil: 16, airNight: 13, airDay: 18 },
        frostTolerance: "none",
        seedingWeeksBeforePlanting: 3,
        tips: "PLANTATION : Mai-Juin (APRÈS GELÉES). CULTURE GOURMANDE : Eau + nutriments. PAILLAGE : Épais 15cm conserve humidité (besoin majeur). PERMACULTURE : Tuteurer ou palisser (gain place, fruits droits). Arrosage régulier ESSENTIEL (amertume si stress hydrique). AMERTUME : Causée par cucurbitacines (stress eau/température). Variétés modernes moins amères. RÉCOLTE : Jeune 15-20cm, quotidienne.",
        variety: "traditionnelle"
    },

    poireau: {
        name: "Poireau",
        icon: "🧅",
        category: "poireau",
        family: "alliacees",
        growthDays: 150,
        spacing: 15,
        maxHeight: 0.8,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil à mi-ombre",
        soilType: "Riche, frais, profond",
        nutrients: "Compost",
        plantingPeriod: "Mars-Mai",
        harvestPeriod: "Août-Avril",
        goodCompanions: ["carotte_nantaise", "tomate_cerise"],
        badCompanions: ["pois", "haricot_vert_nain", "feve", "betterave"],
        seedingTemp: { min: 10, ideal: 18, max: 24 },
        plantingTemp: { soil: 10, airNight: 5, airDay: 10 },
        frostTolerance: "excellent",
        tips: "PLANTATION : Février-Mai (semis) ou Juin-Juillet (plantation). BLANCHIMENT : Butter progressivement ou planter profond (15-20cm) pour long fût blanc. PAILLAGE : Après buttage. PERMACULTURE : Habiller plants (couper 1/3 feuilles + racines) avant plantation. Repousse mouche carotte. VARIÉTÉS : Été (récolte précoce), Automne, Hiver (rustique). Résiste -10°C. ASTUCE : Culture longue, lente, patient. Récolte selon besoins.",
        variety: "traditionnelle"
    },

    fraise: {
        name: "Fraise",
        icon: "🍓",
        category: "fraise",
        family: "rosacees",
        growthDays: 120,
        spacing: 35,
        maxHeight: 0.3,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Riche, légèrement acide (pH 5.5-6.5)",
        nutrients: "Compost mûr, potasse",
        plantingPeriod: "Mars-Avril, Août-Septembre",
        harvestPeriod: "Mai-Octobre",
        goodCompanions: ["oignon", "ail", "laitue_batavia", "epinard", "thym"],
        badCompanions: ["chou"],
        seedingTemp: { min: 15, ideal: 20, max: 25 },
        plantingTemp: { soil: 10, airNight: 5, airDay: 10 },
        frostTolerance: "good",
        tips: "PLANTATION : Août-Septembre (plantation stolons). PAILLAGE ESSENTIEL : Paille (d'où le nom !) garde fruits propres, limite limaces, conserve humidité. PERMACULTURE : Stolons = multiplication gratuite (couper ou replanter). Renouveler plants tous les 3-4 ans (production décline). AIL protège maladies. VARIÉTÉS : Remontantes (plusieurs récoltes), Non-remontantes (une grosse récolte). ARROSAGE : Goutte-à-goutte idéal (évite pourriture). ASTUCE : Filet anti-oiseaux.",
        variety: "traditionnelle"
    },

    fenouil: {
        name: "Fenouil",
        icon: "🥬",
        category: "fenouil",
        family: "apiacees",
        growthDays: 90,
        spacing: 30,
        maxHeight: 0.8,
        waterNeeds: "moyen (2-3 L/m²/jour)",
        sunlight: "Plein soleil",
        soilType: "Léger, frais, drainant",
        nutrients: "Modéré",
        plantingPeriod: "Avril-Juillet",
        harvestPeriod: "Juillet-Octobre",
        goodCompanions: [],
        badCompanions: ["tomate_cerise", "haricot_vert_nain", "pois", "chou"],
        seedingTemp: { min: 12, ideal: 18, max: 25 },
        plantingTemp: { soil: 10, airNight: 8, airDay: 12 },
        frostTolerance: "light",
        tips: "PLANTATION : Avril-Juillet. ALLÉLOPATHIE NÉGATIVE : Inhibe croissance voisins → planter ISOLÉ. PAILLAGE : 5cm. PERMACULTURE : Monte en graine si chaleur excessive ou stress eau. Butter pour blanchir bulbe (plus tendre, moins amer). Arrosage régulier. VARIÉTÉS : Bulbe (légume), Commun (herbe). SAVEUR : Anisée prononcée. ASTUCE : Récolte dès bulbe 8-10cm diamètre.",
        variety: "traditionnelle"
    }
};
